# Generated by Django 2.1.10 on 2020-03-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='gamestore/placeholder.png', upload_to='gamestore/'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gamestore.Game'),
        ),
    ]
