# Generated by Django 2.1.10 on 2021-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(default='apewives/unknown.png', upload_to='apewives')),
                ('apewives_title', models.CharField(default='', max_length=20)),
                ('apewives_image', models.ImageField(default='apewives/unknown.png', upload_to='apewives')),
                ('about_the_apewives', models.CharField(default='', max_length=50)),
                ('about_the_apewives_description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SlidingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliding_images', models.ImageField(default='apewives/unknown.png', upload_to='apewives')),
            ],
        ),
        migrations.CreateModel(
            name='SlidingTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
