# Generated by Django 2.1.10 on 2021-11-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0002_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='image',
            field=models.ImageField(default='apewives/unknown.png', upload_to='apewives/images/'),
        ),
    ]
