# Generated by Django 2.1.10 on 2020-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
