# Generated by Django 2.1.10 on 2022-01-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtab', '0003_auto_20220106_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=50)),
                ('tab_text', models.TextField(blank=True)),
            ],
        ),
    ]
