# Generated by Django 2.1.10 on 2021-10-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_id', models.IntegerField(default=0)),
                ('about_header1', models.CharField(max_length=500, null=True)),
                ('about_description1', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(default='client/unknown.png', upload_to='client/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('hero_image', models.ImageField(default='main/unknown.png', upload_to='hero/')),
                ('logo_image', models.ImageField(default='main/unknown.png', upload_to='hero/')),
                ('testimonial_background_image', models.ImageField(default='main/unknown.png', upload_to='testimonial/')),
                ('contact_email_header', models.CharField(max_length=40, null=True)),
                ('hero_title', models.CharField(max_length=100, null=True)),
                ('hero_sub_title', models.CharField(max_length=100, null=True)),
                ('hero_youtube_link', models.CharField(max_length=100, null=True)),
                ('hero_description', models.CharField(max_length=500, null=True)),
                ('hero_watch_title', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('address3', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('faq_title', models.CharField(max_length=100, null=True)),
                ('faq_description', models.CharField(max_length=500, null=True)),
                ('pricing_title', models.CharField(max_length=100, null=True)),
                ('pricing_description', models.CharField(max_length=500, null=True)),
                ('service_title', models.CharField(max_length=100, null=True)),
                ('service_description', models.CharField(max_length=500, null=True)),
                ('team_title', models.CharField(max_length=100, null=True)),
                ('team_description', models.CharField(max_length=500, null=True)),
                ('about_image', models.ImageField(default='about/unknown.png', upload_to='about/')),
                ('about_image1', models.ImageField(default='about/unknown.png', upload_to='about/')),
                ('about_title', models.CharField(max_length=100, null=True)),
                ('about_description', models.CharField(max_length=500, null=True)),
                ('about_header', models.CharField(max_length=100, null=True)),
                ('about_header_description', models.CharField(max_length=500, null=True)),
                ('about_description2', models.CharField(max_length=500, null=True)),
                ('portfolio_title', models.CharField(max_length=100, null=True)),
                ('portfolio_description', models.CharField(max_length=500, null=True)),
                ('contact_us_title', models.CharField(max_length=100, null=True)),
                ('contact_us_description', models.CharField(max_length=500, null=True)),
                ('subscribe_title', models.CharField(max_length=100, null=True)),
                ('subscribe_description', models.CharField(max_length=500, null=True)),
                ('Copyright_name', models.CharField(max_length=100, null=True)),
                ('designer_name', models.CharField(max_length=500, null=True)),
                ('designer_link', models.CharField(max_length=500, null=True)),
                ('footer_links_title', models.CharField(max_length=100, null=True)),
                ('footer_links_description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_us_title', models.CharField(max_length=50, null=True)),
                ('contact_us_description', models.CharField(max_length=50, null=True)),
                ('class_style', models.CharField(max_length=50, null=True)),
                ('icon_name', models.CharField(max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts_title', models.CharField(max_length=50, null=True)),
                ('class_style', models.CharField(max_length=50, null=True)),
                ('icon_name', models.CharField(max_length=50, null=True)),
                ('data_pure_counter_end', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Likeservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=50, null=True)),
                ('l_service_header', models.CharField(max_length=500, null=True)),
                ('l_service_description', models.CharField(max_length=500, null=True)),
                ('l_service_data_delay', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_service', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_port_name', models.CharField(max_length=50, null=True)),
                ('li_port_name_capital', models.CharField(max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolioli', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_image', models.ImageField(default='port/unknown.png', upload_to='port/')),
                ('port_name', models.CharField(max_length=50, null=True)),
                ('port_name_capital', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_header', models.CharField(max_length=500, null=True)),
                ('row_id', models.IntegerField(default=0)),
                ('row1', models.CharField(max_length=100, null=True)),
                ('row2', models.CharField(max_length=500, null=True)),
                ('row3', models.CharField(max_length=500, null=True)),
                ('row4', models.CharField(max_length=500, null=True)),
                ('row5', models.CharField(max_length=500, null=True)),
                ('row6', models.CharField(max_length=500, null=True)),
                ('price_data_delay', models.IntegerField(default=0)),
                ('number', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='bizland.Companies')),
            ],
            options={
                'verbose_name': 'received_message',
                'verbose_name_plural': 'received_messages',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=50, null=True)),
                ('class_style', models.CharField(max_length=50, null=True)),
                ('service_header', models.CharField(max_length=500, null=True)),
                ('service_description', models.CharField(max_length=500, null=True)),
                ('service_data_delay', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50, null=True)),
                ('skill_counter', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=0)),
                ('Image', models.ImageField(upload_to='team/')),
                ('name', models.CharField(max_length=500, null=True)),
                ('rank_title', models.CharField(max_length=500, null=True)),
                ('team_data_delay', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_image', models.ImageField(default='testimonial/unknown.png', upload_to='testimonial/')),
                ('testimonial_name', models.CharField(max_length=500, null=True)),
                ('testimonial_rank', models.CharField(max_length=500, null=True)),
                ('testimonial_description', models.CharField(max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='bizland.Companies')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='bizland.Companies'),
        ),
        migrations.AddField(
            model_name='about',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='bizland.Companies'),
        ),
    ]
