# Generated by Django 2.1.10 on 2021-10-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='hero_youtube_link',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
