# Generated by Django 3.1.13 on 2021-12-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bizlandmainweb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.IntegerField(default='07')),
                ('welcome_phrase', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_phrase_description', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
