# Generated by Django 2.1.10 on 2021-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlandpractice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizlandmainweb',
            name='company_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bizlandmainweb',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bizlandmainweb',
            name='welcome_phrase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bizlandmainweb',
            name='welcome_phrase_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bizlandmainweb',
            name='youtube_link',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
