# Generated by Django 2.1.10 on 2021-12-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlandpractice', '0002_auto_20211208_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlandmainweb',
            name='main_image',
            field=models.ImageField(default='biz/unknown.png', upload_to='biz'),
        ),
    ]
