# Generated by Django 2.1.10 on 2021-12-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizlandpractice', '0004_featuredservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlandmainweb',
            name='about_description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bizlandmainweb',
            name='about_image',
            field=models.ImageField(default='biz/unknown.png', upload_to='biz'),
        ),
        migrations.AddField(
            model_name='bizlandmainweb',
            name='about_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featuredservices',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fs', to='bizlandpractice.BizlandMainWeb'),
        ),
    ]
