# Generated by Django 2.1.10 on 2021-12-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizlandpractice', '0005_auto_20211209_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlandmainweb',
            name='about_description2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bizlandmainweb',
            name='about_description3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bizlandmainweb',
            name='about_title2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featuredservices',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fs', to='bizlandpractice.BizlandMainWeb'),
        ),
    ]
