# Generated by Django 2.1.10 on 2022-02-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizlandpractice', '0011_auto_20220120_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfl',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abfl', to='bizlandpractice.BizlandMainWeb'),
        ),
        migrations.AlterField(
            model_name='featuredservices',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fs', to='bizlandpractice.BizlandMainWeb'),
        ),
    ]
