# Generated by Django 2.1.10 on 2021-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=100)),
                ('town_clerk_fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('order', models.SmallIntegerField(default=0)),
                ('Image', models.ImageField(upload_to='ugandatowns/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
