# Generated by Django 2.1.10 on 2021-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=50)),
                ('town_clerk_full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(default='ugandatowns/unknown.png', upload_to='ugandatowns/')),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
