# Generated by Django 2.1.10 on 2021-03-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towns',
            options={'ordering': ['order']},
        ),
    ]
