# Generated by Django 2.1.10 on 2022-01-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(blank=True, max_length=50)),
                ('img2', models.ImageField(default='equipment/unknown.png', upload_to='equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title3', models.CharField(blank=True, max_length=50)),
                ('img3', models.ImageField(default='equipment/unknown.png', upload_to='equipment')),
            ],
        ),
        migrations.RenameModel(
            old_name='Equipments',
            new_name='Equipments1',
        ),
        migrations.RenameField(
            model_name='equipments1',
            old_name='image',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='equipments1',
            old_name='title',
            new_name='title1',
        ),
    ]
