# Generated by Django 2.1.10 on 2022-01-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtab', '0002_auto_20220106_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=50)),
                ('title2', models.CharField(blank=True, max_length=50)),
                ('title3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipments1',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='equipments2',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='equipments3',
            name='title3',
        ),
    ]
