# Generated by Django 2.1.10 on 2022-02-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtab', '0004_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabs',
            name='atm_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tabs',
            name='tab_text_function',
            field=models.TextField(blank=True),
        ),
    ]
